### ISSUE TITLE
Extended button problem

### ISSUE THREAD

**Issue by jenstornell** [medienbaecker/kirby-enhanced-textarea#1]
I've created a field that extends the textarea field. It also works quite well with this field. One thing does not work and that is the modal button to the right. It says `Error Invalid field`.

**Splitfield (will change name later on)**

Require 2.3 beta.

https://github.com/jenstornell/kirby-splitfield

1. Install it as a plugin. It registers a new field.
1. Add a field in the blueprint and set `type: splitfield`.

Hopefully we can solve this issue together? If it works well I want to recommend to use your field together with my plugin.

***Sidenote: What my plugin does is a live preview when writing in the textarea***

**Comment by medienbaecker** [comment]
Oh, that's an amazing idea. That's like the perfect compromise between the regular textarea and the (sometimes buggy) Visual Markdown Editor.

I'm going to install the splitfield plugin and try to solve the issue. Hang on.

**Comment by medienbaecker** [comment]
Seems like the "Link" and "Email" buttons are missing, too. But that issue is also present with the regular "textarea" field. Do you just want to display the bold and italic buttons?

**Comment by jenstornell** [comment]
@medienbaecker Yes, I've hide them temporarly. I had an issue with the link and email as well. Maybe it's the same issue, hard for me to tell. If you would help to figure it out, it would be really helpful.

**Some notes about my field:**

- Does not work in Edge browser.
- Works with multiple fields.
- Works inside a structure field.
- Blueprint option to add an own CSS file to a field (really powerful wysiwyg).
- Blueprint option to disable preview button bar.
- Blueprint option to disable preview padding.
- Blueprint option to lock the preview (visible all the time).

**Comment by medienbaecker** [comment]
@jenstornell Alright. The "pagelink" button and modal work exactly the same as the "link" and "email". I just copied the files and changed the modal content.

I'll try to figure out why the field is "invalid". Maybe it has something to do with the changed div classes around the textarea. Maybe the modal can't figure out where's the textarea. Let's see...

**Comment by jenstornell** [comment]
I fixed it. Instead of this:

```
/panel/pages/home/field/test1/textarea/link
```

I needed to link to:

```
/panel/pages/home/field/test1/splitfield/link
```

Then I needed to copy `controller.php` and replace:

```
class TextareaFieldController extends Kirby\Panel\Controllers\Field {
```

with:

```
class SplitfieldFieldController extends Kirby\Panel\Controllers\Field {
```

Except for this, I also needed to copy forms and views.

**Comment by medienbaecker** [comment]
Perfect, I suspected an issue with the "textarea" vs. "splitfield" name. I didn't think of the `controller.php`at all, but it definitely makes sense.

**Comment by jenstornell** [comment]
I had a fully working "reveal" field but when I tried it, it did not work that well in a real live production environment. Now I'm at it again.

- It will look more like my Splitview plugin but with less features. A splitview from inside.
- It will not touch much in the textarea field. This field will work as well as other similar.

**Teaser**

Notice the arrow:

![image](https://cloud.githubusercontent.com/assets/927011/15568161/a1fc0ebe-232a-11e6-80aa-777ed3c4e558.png)

One question for you...

Is this repo dead? There are issues but no updates.

**Comment by medienbaecker** [comment]
The repository is not dead at all, I just hadn't had the time to deal with the issues yet. The field is working fine, all the issues are just enhancements and rather "nice to have". I use this textarea field on every client project right now.

Your minimal splitview plugin looks promising!
