### ISSUE TITLE
Default buttons

### ISSUE THREAD

**Issue by medienbaecker** [medienbaecker/kirby-enhanced-textarea#10]

**Comment by jenstornell** [comment]
**For a default set I vote for:**

- h1
- h2
- h3
- B
- I
- UL
- OL
- Link
- Pagelink

I use all of them.

The email icon is default even in the textarea in Kirby. I don't understand that. Do you link to mail addresses in every page you have? I don't. I maybe link to an email on two pages on a whole site. I would not have the email as default.

**Comment by heyallan** [comment]
I wouldn't have h1 as default because that's usually set via title field before one gets to the textarea.
I've never created an h1 from any textarea.

**Comment by medienbaecker** [comment]
In version 1.4 you can now decide yourself what default buttons you want to display:
```
c::set('textarea.buttons', array(
  "h2",
  "h3",
  "bold",
  "italic",
  "ulist",
  "olist",
  "link",
  "page"
));
```
