### ISSUE TITLE
Textarea does not work in structure field

### ISSUE THREAD

**Issue by medienbaecker** [medienbaecker/kirby-enhanced-textarea#11]
Only the "bold" and "italic" buttons are visible because you can't open a modal inside a modal. I think the h1-h3 and list icons should be visible though.

**Comment by medienbaecker** [comment]
I'm experimenting with an "inline" editor for the buttons that require a modal right now. This could display all the possible attributes with help texts. According to the type of the attribute, a text field, select field or toggle will be displayed.

WIP:

![page](https://cloud.githubusercontent.com/assets/7975568/16159676/5c619e7c-34c4-11e6-865d-334373f0ad8c.png)
![link](https://cloud.githubusercontent.com/assets/7975568/16159679/5da88034-34c4-11e6-92f3-a68749c7f69e.png)

**Comment by samnabi** [comment]
I love this inline editor concept. It looks like a native panel field.

**Comment by jenstornell** [comment]
Is it still a textarea? Or a content div?

**Comment by Andi-Lo** [comment]
Any progress on this one :)?

**Comment by medienbaecker** [comment]
Sadly this is more complicated than it looks. It's not possible to insert stuff like that in a `textarea` so I'd have to emulate it with a `div` and it's a lot of work to do that properly.
