### ISSUE TITLE
Page modal "disappears" when page list is long-ish

### ISSUE THREAD

**Issue by texnixe** [medienbaecker/kirby-enhanced-textarea#12]

**Comment by medienbaecker** [comment]
Do you have an example page tree for this? Long-ish page names or many pages?

**Comment by texnixe** [comment]
Longer list of pages, see screenshot
![capture d ecran 2017-05-16 a 09 27 54](https://cloud.githubusercontent.com/assets/5312492/26094401/28d85134-3a1a-11e7-97e6-bc41f30fac82.png)

Have to check if another plugin interferes…

**Comment by medienbaecker** [comment]
Can you try updating to the latest version of this field? I switched to the larger, wider modal like a `modalsize: large` structure.

I guess there are more pages hidden outside the viewport? I'll try to reproduce it with a lot of pages and maybe I'll have to change the vertical centering somehow. Do you know by chance where the negative `margin-top` comes from? Is there a centering script somewhere?

**Comment by texnixe** [comment]
The newer version doesn't change anything for me. I have now removed everything that I thought might interfere, but it seems to be the javascript that creates the negative margin. I'll try again with a fresh kit later to make sure it's not something in this project that I messed up.

**Comment by medienbaecker** [comment]
I just pushed another version and I think I've resolved the issue. I searched for the native `center` method in the core and found a way to re-trigger it. Can you check if this works for you?
I also added a `package.json` and changed the folder structure so you don't have to replace it manually.

**Comment by texnixe** [comment]
Yes, that seems to work, thanks for the fast fix 😄. 

The field is installed with the wrong folder name when installing via the CLI, though…

**Comment by medienbaecker** [comment]
Perfect!

Oops, you're right! I just fixed the field name.

**Comment by medienbaecker** [comment]
@texnixe Sorry, I didn't see your question right away. I don't have any plans in that direction unfortunately. I used the Visual Markdown Editor for a long time but finally decided to create my own textarea replacement as it became more and more buggy and was no longer developed. But I added a pull request in 2015 regarding the page link functionality, maybe that helps you: https://github.com/JonasDoebertin/kirby-visual-markdown/pull/72

Most of my clients find the pure markdown intimidating at first but most will learn to love it at some point.

**Comment by texnixe** [comment]
Oh, I thought I had read that somewhere, so I thought I'd ask. Well, as much as I love markdown personally, for some clients it might still be easier with a more visual approach. At least your enhanced textarea makes it easy to add the most important tags, and maybe I can add some custom Kirbytags to the list, we'll see…
