### ISSUE TITLE
Undo/Redo

### ISSUE THREAD

**Issue by medienbaecker** [medienbaecker/kirby-enhanced-textarea#15]
Support `Cmd Z` / `Ctrl Z` to undo making a text bold, italic, inserting a link, ...

**Comment by medienbaecker** [comment]
This function is now ready in the [undo branch](https://github.com/medienbaecker/kirby-enhanced-textarea/tree/undo). I will have to test this some more, though. Browser support is very sparse for this kind of functionality.

**Comment by jenstornell** [comment]
Undo/redo button support as well?

**Comment by medienbaecker** [comment]
That would be a nice addition to the non-default buttons. I won't add it to the default button set as I think most users know the shortcuts. But it's probably a good idea being able to show them for some clients.
