### ISSUE TITLE
How to add new custom buttons?

### ISSUE THREAD

**Issue by BlueberryPuppyKisses** [medienbaecker/kirby-enhanced-textarea#19]
@medienbaecker 
Is there a way to add new buttons to the plugin?

would be great if there's a clickable way editors could go for:

- vimeo:  `(vimeo: http://vimeo.com/1111111)`
- youtube:  `(youtube: http://youtube.com/1111111)`
- image `(image: photo.jpg)`

**Comment by medienbaecker** [comment]
Sorry for answering so late! I didn't see your issue in my notifications.

As you listed three Kirbytags you could maybe have a look at the autocomplete feature: https://github.com/medienbaecker/kirby-enhanced-textarea#new-feature-in-16-confetti_ball-autocomplete-for-kirbytags-confetti_ball

Adding custom buttons to the plugin is possible, but not very straight forward. I'd like to add a possibility to add custom buttons via a plugin, as mentioned in issue https://github.com/medienbaecker/kirby-enhanced-textarea/issues/13 but it's not that easy. At least for me.

If you want to add a button in the plugin core you could have a look at these lines: https://github.com/medienbaecker/kirby-enhanced-textarea/blob/master/buttons.php#L217-L222
