### ISSUE TITLE
Both H has the same size

### ISSUE THREAD

**Issue by jenstornell** [medienbaecker/kirby-enhanced-textarea#2]
In my setup both the H has the same size. It can be a style issue with Kirby 2.3 beta. Not sure.

![kirby starterkit panel](https://cloud.githubusercontent.com/assets/927011/14883147/c293d7dc-0d3c-11e6-8851-b195993256d7.png)

**Comment by medienbaecker** [comment]
I tried it with the Kirby 2.3 beta and it works for me. The file that's responsible for that style change is the [editor.css](https://github.com/medienbaecker/kirby-enhanced-textarea/blob/master/textarea/assets/css/editor.css#L4-L6). Can you inspect the second "H" button and look at the styles? Maybe somethings gets overwritten. It looks like that for me:

![screenshot 2016-04-28 12 36 51](https://cloud.githubusercontent.com/assets/7975568/14883310/f077a33a-0d3d-11e6-8f6f-d24ea665a637.png)

**Comment by jenstornell** [comment]
It says `field-button-h2` but both of them uses `fa-header` as icon. Maybe it should be like that?

![image](https://cloud.githubusercontent.com/assets/927011/14883710/fd95b4b0-0d3f-11e6-98c0-b26e62ad1bfe.png)

I've also tried it without extending it with my field with the same result.

**Comment by medienbaecker** [comment]
The `li` should get a font-size of 0.75em. Can you select the li and look at the Styles sidebar please?

**Comment by jenstornell** [comment]
Font size on that element is missing in the developer tool. I also updated the Kirby to nightly, no difference. I checked you css file, it's there.

**Comment by jenstornell** [comment]
The new icons solves this issue.
