### ISSUE TITLE
Complete rewrite with SimpleMDE

### ISSUE THREAD

**Issue by medienbaecker** [medienbaecker/kirby-enhanced-textarea#23]
I should stop extending the core textarea field. There are some limitations I can only overcome by starting from scratch.

[Here](https://github.com/medienbaecker/kirby-simplemde)'s a very bare bones rewrite using [SimpleMDE](https://simplemde.com/).

![preview](https://user-images.githubusercontent.com/7975568/33186314-de426910-d088-11e7-914a-10e874fd0cef.gif)

**Comment by jenstornell** [comment]
Or save your ideas for Kirby 3? But I really like SimpleMDE, so go for it! =)

**Comment by S1SYPHOS** [comment]
I thought there's just one thing to be improved: fixed positioning of the button bar. But looking at your SimpleMDE plugin, I was surprised to like it even more!

Keep up the good work, and thank you very much for yet another useful Kirby plugin.
