### ISSUE TITLE
Strange modal

### ISSUE THREAD

**Issue by jenstornell** [medienbaecker/kirby-enhanced-textarea#3]
I used a normal textarea this time and not an extended one. I've deactivated my plugin just to be sure nothing else affects this. I got this when I click the modal:

The link and email buttons work. It's your custom one that does not.

![image](https://cloud.githubusercontent.com/assets/927011/14883943/dbcb99d8-0d41-11e6-98be-de9b8ac1e6b8.png)

**Comment by medienbaecker** [comment]
I still can't reproduce this on any of my installations. 😞

**Comment by jenstornell** [comment]
I found your "bug". In `pagelink.php` line 31 you have `<?` which is a short version of `<?php`. Often the short version is disabled on the server. Therefor I really think you should use `<?php` instead.

Maybe it's on more places. I have not checked. Thanks!

**Comment by medienbaecker** [comment]
Ah, thank you very much! I searched everywhere. Damn these short opening tags 😠
