### ISSUE TITLE
Alternative H icon

### ISSUE THREAD

**Issue by jenstornell** [medienbaecker/kirby-enhanced-textarea#4]
http://fortawesome.github.io/Font-Awesome/icon/hashtag/

Maybe a big H is better than #? I'm not sure, I just wanted to give you an alternative. Hash says a little more of what the outcome in the text will be. It's not going to be `H` in the textarea, so H is in that context may be a little off.

If using the hash icon, maybe just let the hashes be the same size between eachother like `##` for what now is little H?

**Comment by medienbaecker** [comment]
Thanks for the suggestion. You're right, `#` is what's going to be inserted. But if you look at the **b**old and **i**talic icons it would be something different.

I just pushed "H1" and "H2" buttons with the same font size. Do you think that works?

**Comment by jenstornell** [comment]
I love it! I had that in mind as well, but I lost it somewhere on the way. Great mind reading!

It's perfect!
