### ISSUE TITLE
H3 support?

### ISSUE THREAD

**Issue by jenstornell** [medienbaecker/kirby-enhanced-textarea#5]
There is no `H3`? I don't think `h4-h6` is needed but I use `H3` quite often.

If it will feels bloated as default, maybe add it as a blueprint option?

**Comment by medienbaecker** [comment]
Definitely, I don't know why I just took the two headline buttons from the Visual Markdown Editor.
My clients were always a bit confused to just write the third "#".

I think I could somehow define a default set of buttons. So you can add the `h3` like that
```
buttons:
  - h1
  - h2
  - h3
```

**Comment by jenstornell** [comment]
Yes, it's already possible to set upp the buttons like that, choosing that to have, except for the h3 that is missing.

Also a post about it here:

https://forum.getkirby.com/t/back-to-the-basics-for-the-textarea-field/3625/7

**Comment by medienbaecker** [comment]
I'll keep h1–h3 as default buttons for now. I don't seem to find a quick and easy way to change the default buttons for now. I think this is the function that's responsible: https://github.com/getkirby/panel/blob/master/app/fields/textarea/buttons.php
