### ISSUE TITLE
Smarter H function?

### ISSUE THREAD

**Issue by jenstornell** [medienbaecker/kirby-enhanced-textarea#6]
Your H-function works just like Kirby 1. Maybe you copied it?

What I don't like about it is this:

```
Some h1 heading |
```

The pipe is to illustrate my cursor.

When I click H1, I expect this:

```
# Some h1 heading
```

But I'll get this:

```
Some h1 heading #
```

The hash should always be first in a row to create a headline.

Maybe it's tricky to solve it. Just an idea.

If it's to hard to solve, just close it.

**Comment by medienbaecker** [comment]
That's on my to do list. I want it to behave like the headline buttons in the Visual Markdown Editor.

**Comment by jenstornell** [comment]
I don't know how they work over there but I've used WordPress too much.

In WordPress the whole row is converted to a h1. WordPress uses html instead of markdown, but anyway. The principle is the same. It does not care where on that row the cursor is. It also work like that in Word or other document editors.

Would be really cool if you solved it.

**Comment by jenstornell** [comment]
If solved, it should also apply to ul, li, blockquote.

**Comment by medienbaecker** [comment]
Yes, I commented on that in the [forums](https://forum.getkirby.com/t/back-to-the-basics-for-the-textarea-field/3625/12?u=thguenther).

I'd also like to have an auto "- " or "2. " for a new line at some point. But that's not as important.

**Comment by jenstornell** [comment]
The auto `-` would be nice but I don't agree with `2.` because in markdown every new ordered list item starts with `1.`

```
1. First
1. Second
1. Third
```

1. Here
1. Is
1. My
1. Proof

**Comment by medienbaecker** [comment]
Oh, I didn't know that. Nice!
The Visual Markdown Editor does the auto-increment so I always thought it would be essential.

**Comment by jenstornell** [comment]
In fact it's better to only use `1.` because it's less confusing, as the markdown handle this when parsing it.

**Comment by medienbaecker** [comment]
I just pushed the first commit concerning this issue. I'm still working on the intelligent list function, but the header function is done already.

![headline](https://cloud.githubusercontent.com/assets/7975568/26098435/0309b336-3a28-11e7-86f8-0bc6315ddcc0.gif)

**Comment by medienbaecker** [comment]
The intelligent list function works now too and I can finally close this issue. I have not yet tested it in IE so I will probably open another issue for that.

It's quite handy now, you don't even have to select the whole line as the script finds new lines automatically:

![lists](https://cloud.githubusercontent.com/assets/7975568/26103457/d4f71300-3a39-11e7-96f7-5d401f9efcfc.gif)
