### ISSUE TITLE
Extended optional button - Blockquote

### ISSUE THREAD

**Issue by jenstornell** [medienbaecker/kirby-enhanced-textarea#9]
I read that you are about to implement list buttons. I think that's really nice. Not every button should be set as default, but it's great to have by option.

I button I like is blockquote, it's a > character before the text. Would be easy to implement as well. Just like a header.

**Comment by medienbaecker** [comment]
Oh right, that would be helpful too. As [I commented on the h3-issue](https://github.com/medienbaecker/kirby-enhanced-textarea/issues/5#issuecomment-215581407) I'm still trying to figure out how to set default buttons. The textarea field simply takes every button as a default.

**Comment by jenstornell** [comment]
You have this code:

```php
public function content() {

    $content = parent::content();

    if($this->buttons and !$this->readonly) {
      $content->append($this->buttons());
    }

    return $content;

  }
```

If I remember correctly `$this->buttons()` include a html list of buttons. Maybe look at that output copy it and instead use your own template for it?
